-- Conectar ao PDB correto (ajuste conforme sua configuração)
ALTER SESSION SET CONTAINER = ORCLPDB1;

-- HR (Human Resources)
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER hr IDENTIFIED BY hr DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO hr';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/
COMMIT;

-- OE (Order Entry) 
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER oe IDENTIFIED BY oe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, UNLIMITED TABLESPACE TO oe';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/
COMMIT;

-- PM (Product Media)
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER pm IDENTIFIED BY pm DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, UNLIMITED TABLESPACE TO pm';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/
COMMIT;

-- IX (Information Exchange)
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER ix IDENTIFIED BY ix DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, UNLIMITED TABLESPACE TO ix';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/
COMMIT;

-- SH (Sales History)
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER sh IDENTIFIED BY sh DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, UNLIMITED TABLESPACE TO sh';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/
COMMIT;

-- BI (Business Intelligence)
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER bi IDENTIFIED BY bi DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO bi';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/
COMMIT;

-- CO (Customer Orders) - se você planeja usar este schema também
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER co IDENTIFIED BY co DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO co';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/
COMMIT;

-- Conceder privilégios adicionais necessários para alguns schemas
BEGIN
   EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO oe';
   EXECUTE IMMEDIATE 'GRANT QUERY REWRITE TO sh';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

COMMIT;