PROMPT Granting permissions to users...
ALTER SESSION SET CONTAINER = ORCLPDB1;

-- HR (Human Resources)
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO hr;

-- OE (Order Entry)
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO oe;

-- PM (Product Media)
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO pm;

-- IX (Information Exchange)
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO ix;

-- SH (Sales History)
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO sh;

-- BI (Business Intelligence)
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO bi;

-- CO (Customer Orders)
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, UNLIMITED TABLESPACE TO co;
