ALTER SESSION SET CONTAINER = XEPDB1;

-- HR
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER hr IDENTIFIED BY hr DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN -- ignora "usuário já existe"
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE TO hr';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

-- OE
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER oe IDENTIFIED BY oe DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE TO oe';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

-- SH
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER sh IDENTIFIED BY sh DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE TO sh';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/
