PROMPT Granting permissions to users...
ALTER SESSION SET CONTAINER = XEPDB1;

SHOW USER;

GRANT CREATE SESSION, CREATE TABLE, DROP USER TO HR;
GRANT CREATE SESSION, CREATE TABLE, DROP USER, DROP DIRECTORY TO OE;
GRANT CREATE SESSION, CREATE TABLE, DROP USER TO SH;
