services:
  oracle:
    build: .
    container_name: oracle-xe-18c
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_PDB: XEPDB1
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data: